Repository Erda-FE/dashboard-configuration, pull requests merged in 2021-11, with the labels that each got.

#38 Feature/v2
  .npmrc
  README.md
  package-lock.json
  package.json
  src/common/DcFormBuilder/index.tsx
  src/common/DcFormModal/index.tsx
  src/common/form-builder/fields.tsx
  src/common/form-builder/form-builder.tsx
  src/common/form-builder/index.tsx
  src/common/form-builder/readonly-field.tsx
  src/common/utils/agent.js
  src/common/utils/agent.ts
  src/common/utils/client.ts
  src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/create-alias-modal.tsx
  src/components/DcChartEditor/data-config/dice-form/dimensions-configurator/dimension-configs.tsx
  src/components/DcChartEditor/data-config/dice-form/index.tsx
  src/components/DcChartEditor/editor-panel/index.scss
  src/components/DcCharts/chart-map/index.tsx
  src/components/DcContainer/options.tsx
  src/components/DcGlobalFilters/config-modal.tsx
  src/services/chart-editor.ts
  src/types/global.d.ts
  webpack.analyze.js
  webpack.config.js
  webpack_ts.loader.js
Labels: refactor

#41 fix: fix zero will transform to undefined in dashboard
  src/common/utils/replace-variable.ts
Labels: bugfix

#42 Fix: submit dashboard editor check
  src/common/form-builder/fields.tsx
  src/components/DcChartEditor/data-config/dice-form/index.tsx
  src/components/DcChartEditor/editor-panel/index.tsx
  src/stores/chart-editor.ts
Labels: bugfix

#43 docs: upgrade changeLog to v2.0.0
  CHANGELOG.md
  package.json
Labels: documentation

#45 chore: update changeLog and package.json
  CHANGELOG.md
  package.json
Labels: documentation

#46 fix: i18n impact erda-ui error
  src/components/DcBoard/index.tsx
  src/components/DcBoard/pure-board.tsx
  src/utils/locale.ts
  src/utils/locale.tsx
Labels: bugfix

#47 docs: update changeLog and package.json
  CHANGELOG.md
  package.json
Labels: documentation

#48 fix: display no mask when did not complete required fields
  src/components/DcChartEditor/editor-panel/index.tsx
  src/components/DcContainer/index.tsx
  src/constants/index.ts
  src/stores/chart-editor.ts
Labels: bugfix

#49 fix: update changeLog and package.json
  CHANGELOG.md
  package.json
Labels: documentation
